---
language: objective-c

sudo: true

before_install:
  # Setup Python environment
  - source tests/terryfy/travis_tools.sh
  - export CC=clang
  - export CXX=clang++
  - get_python_environment macpython 2.7.10 venv

install:
  # Create Workspace directory
  - mkdir -p ~/Workspace/
  - echo "cp -r ../dotfiles ~/Workspace/dotfiles" | sudo -s bash

script:
  # Execute the bootstrapping script
  - cd ~/Workspace/dotfiles
  - echo "./bootstrap.sh --force --no-update" | sudo -s bash
  # Execute the update script
  - cd ~/.ansible
  - export PATH=/opt/homebrew/bin:$PATH
  - echo "FORCE_UNSAFE_CONFIGURE=1 ansible-playbook -i hosts -e '{\"brew_upgrade_all\":false,\"atom_upgrade_all\":false,\"node_upgrade_all\":false}' site.yml" | sudo -s bash
