---
- hosts: localhost
  connection: local
  vars:
    brew_upgrade_all: True
    atom_upgrade_all: True
    node_upgrade_all: True
  pre_tasks:
    - name: Get list of configured files to ignore.
      command: cat {{ dotfiles_local }}/dotignore
      register: dotignore_file
      always_run: yes
      changed_when: False
    - name: Get list of configured Homebrew Taps.
      command: cat {{ dotfiles_local }}/brew_taps
      register: brew_taps_file
      always_run: yes
      changed_when: False
    - name: Get list of configured Homebrew packages.
      command: cat {{ dotfiles_local }}/brew_packages
      register: brew_packages_file
      always_run: yes
      changed_when: False
    - name: Get list of configured Homebrew Cask packages.
      command: cat {{ dotfiles_local }}/cask_packages
      register: cask_packages_file
      always_run: yes
      changed_when: False
    - name: Get list of configured Atom packages.
      command: cat {{ dotfiles_local }}/atom_packages
      register: atom_packages_file
      always_run: yes
      changed_when: False
    - include: tasks/fonts.yml
  roles:
    - {
        role: jgkim.dotfiles ,
        dotfiles_ignore: "{{ dotignore_file.stdout_lines }}"
      }
    - {
        role: jgkim.brew ,
        brew_taps: "{{ brew_taps_file.stdout_lines }}",
        brew_packages: "{{ brew_packages_file.stdout_lines }}",
        cask_packages: "{{ cask_packages_file.stdout_lines }}"
      }
    - {
        role: jgkim.atom,
        atom_packages: "{{ atom_packages_file.stdout_lines }}"
      }
  post_tasks:
    - include: tasks/login_items.yml
    - include: tasks/node_packages.yml
    - include: tasks/docker.yml
    - include: tasks/heroku.yml
