---
- hosts: localhost
  connection: local
  vars:
    brew_upgrade_all: True
    atom_upgrade_all: True
    node_upgrade_all: True
  pre_tasks:
    - include: tasks/load_files.yml
    - include: tasks/fonts.yml
  roles:
    - {
        role: jgkim.dotfiles ,
        dotfiles_ignore: "{{ dotignore_file.stdout_lines }}"
      }
    - {
        role: jgkim.brew ,
        brew_taps: "{{ brew_taps_file.stdout_lines }}",
        brew_packages: "{{ brew_packages_file.stdout_lines }}",
        cask_packages: "{{ cask_packages_file.stdout_lines }}"
      }
    - {
        role: jgkim.atom,
        atom_packages: "{{ atom_packages_file.stdout_lines }}"
      }
  post_tasks:
    - include: tasks/login_items.yml
    - include: tasks/node_packages.yml
    - include: tasks/docker.yml
    - include: tasks/heroku.yml
    - include: tasks/travis.yml
